
name: "Build and Deploy Webclient Api2"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME:   webapptestesmond  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '6.0.100'                    # set this to the .NET Core version to use

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build  **/Apim.WebClient.csproj --configuration Release --no-restore

    - name: Test app
      run: dotnet test --no-build

    - name: Publish app for deploy
      run: dotnet publish  **/Apim.WebClient.csproj --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.webappPublishProfileWebClientApi }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    #  - name: Publish Artifacts
       # uses: actions/upload-artifact@v1.0.0
       # with:
        #  name: webapp
        #  path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
